### ISSUE TITLE
Create loader when page loads

### ISSUE THREAD

**Issue by bogdanszabo** [wearecrunch/CrunchWebsite#2]

**Comment by wearecrunch** [comment]
https://app.asana.com/0/26559586140623/26559586140623 should create the gif
- check this out: http://gifmake.com/
- max. 50 images with the loading process
  - pay attention cause the loader should be looping

[--- Commented from Asana.com
#commenter Bogdan Szabo
---[aa]

**Comment by bogdanszabo** [comment]
See here: a0a98ed01509ac193d52c697170cb03bc3f8b1b7
